spring.datasource.url=jdbc:postgresql://localhost:5432/iqosdb
spring.datasource.username=postgres
spring.datasource.password=postgres

# PostgreSQL 18（最新版）に接続するための「お守り」
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081